import { randomUUID } from 'node:crypto';
import type { Db } from './database.js';
import { readDataset } from './persist.js';
import { enumerateWorkingDays, holidayOccurrences } from '@ecp/shared';
import { buildCapacityContext, readEngineConfig, sprintCapacity } from '@ecp/engine';
import { badRequest, conflict, notFound } from '../http-error.js';
import { buildStoredSprintContext, refreshSprintContext } from '../jira/sprint-context.js';
import type { JiraClient } from '../jira/client.js';

export type CeremonyKind = 'planning' | 'review';
export type CeremonyStatus = 'draft' | 'finalized' | 'completed';
export interface Ceremony { id: string; teamId: string; sprintId: string; sprintName: string; sprintStartDate: string; sprintEndDate: string; kind: CeremonyKind; status: CeremonyStatus; revision: number; activeSnapshotId: string | null; comparisonSnapshotId: string | null; createdAt: string; updatedAt: string; finalizedAt: string | null; }
export interface CeremonyNote { id: string; ceremonyId: string; body: string; targetKind: 'global' | 'metric' | 'epic' | 'member'; targetKey: string | null; targetLabel: string; targetValueJson: string | null; position: number; createdAt: string; updatedAt: string; }
export interface CeremonyAggregate { ceremony: Ceremony; planItems: string[]; notes: CeremonyNote[]; comparisonNotes: CeremonyNote[]; snapshots: Array<{ id: string; version: number; purpose: string; capturedAt: string; source: string; freshness: string; truncated: boolean; payload: unknown }>; comparisonSnapshot: { id: string; purpose: string; payload: unknown } | null; }
const now = () => new Date().toISOString();
const kinds = new Set<CeremonyKind>(['planning', 'review']);
const targetKinds = new Set<CeremonyNote['targetKind']>(['global', 'metric', 'epic', 'member']);
function capacitySnapshot(db: Db, row: any) { const dataset = readDataset(db); const team = dataset.teams.find((entry) => entry.id === row.team_id); if (!team) throw conflict('This ceremony team is no longer available for capacity calculation'); const members = dataset.members.filter((entry) => entry.teamId === team.id); const memberIds = new Set(members.map((entry) => entry.id)); const window = { index: 0, start: row.sprint_start_date, end: row.sprint_end_date, workingDays: enumerateWorkingDays(row.sprint_start_date, row.sprint_end_date, team.workingDays) }; const inputs = { pto: dataset.pto.filter((entry) => memberIds.has(entry.memberId)), oncall: dataset.oncall.filter((entry) => memberIds.has(entry.memberId)), velocityOverrides: dataset.velocityOverrides.filter((entry) => memberIds.has(entry.memberId)), holidays: (dataset.holidays ?? []).filter((entry) => entry.teamId === team.id), oncallMultiplier: readEngineConfig(dataset).oncallMultiplier ?? 0.5 }; const adjustedCapacity = sprintCapacity(window, buildCapacityContext({ members, ...inputs })); return { teamBaseVelocity: members.filter((member) => member.active).reduce((total, member) => total + member.baseVelocity, 0), adjustedCapacity, workingDays: window.workingDays, holidays: holidayOccurrences(inputs.holidays, row.sprint_start_date, row.sprint_end_date).map(({ date, name }) => ({ date, name })), members: members.filter((member) => member.active).map((member) => ({ memberId: member.id, baselineVelocity: member.baseVelocity, adjustedCapacity: sprintCapacity(window, buildCapacityContext({ members: [member], ...inputs })) })), oncallMultiplier: inputs.oncallMultiplier }; }
function ceremony(row: any): Ceremony { return { id: row.id, teamId: row.team_id, sprintId: row.sprint_id, sprintName: row.sprint_name, sprintStartDate: row.sprint_start_date, sprintEndDate: row.sprint_end_date, kind: row.kind, status: row.status, revision: row.revision, activeSnapshotId: row.active_snapshot_id ?? null, comparisonSnapshotId: row.comparison_snapshot_id ?? null, createdAt: row.created_at, updatedAt: row.updated_at, finalizedAt: row.finalized_at ?? null }; }
function note(row: any): CeremonyNote { return { id: row.id, ceremonyId: row.ceremony_id, body: row.body, targetKind: row.target_kind, targetKey: row.target_key ?? null, targetLabel: row.target_label, targetValueJson: row.target_value_json ?? null, position: row.position, createdAt: row.created_at, updatedAt: row.updated_at }; }
function getRow(db: Db, id: string): any { const row = db.prepare('SELECT * FROM sprint_ceremony WHERE id = ?').get(id); if (!row) throw notFound(`Sprint ceremony ${id} not found`); return row; }
function revision(value: unknown): number { if (!Number.isInteger(value) || (value as number) < 0) throw badRequest('expectedRevision must be a non-negative integer'); return value as number; }
function mutable(row: any, expected: number): void { if (row.revision !== expected) throw conflict('This ceremony changed in another tab; reload and try again'); if (row.status !== 'draft') throw conflict('Finalized ceremonies are read-only'); }
export function getCeremony(db: Db, id: string): CeremonyAggregate { const row = getRow(db, id); const snapshots = db.prepare('SELECT * FROM sprint_ceremony_snapshot WHERE ceremony_id = ? ORDER BY version').all(id).map((entry: any) => ({ id: entry.id, version: entry.version, purpose: entry.purpose, capturedAt: entry.captured_at, source: entry.source, freshness: entry.freshness, truncated: entry.truncated === 1, payload: JSON.parse(entry.payload_json) })); const comparison = row.comparison_snapshot_id ? db.prepare('SELECT id, purpose, payload_json FROM sprint_ceremony_snapshot WHERE id = ?').get(row.comparison_snapshot_id) as any : null; const comparisonNotes = row.comparison_snapshot_id ? db.prepare('SELECT n.* FROM sprint_ceremony_note n JOIN sprint_ceremony_snapshot s ON s.ceremony_id = n.ceremony_id WHERE s.id = ? ORDER BY n.position').all(row.comparison_snapshot_id).map(note) : []; return { ceremony: ceremony(row), planItems: db.prepare('SELECT work_item_key FROM sprint_plan_item WHERE ceremony_id = ? ORDER BY position').all(id).map((entry: any) => entry.work_item_key), notes: db.prepare('SELECT * FROM sprint_ceremony_note WHERE ceremony_id = ? ORDER BY position').all(id).map(note), comparisonNotes, snapshots, comparisonSnapshot: comparison ? { id: comparison.id, purpose: comparison.purpose, payload: JSON.parse(comparison.payload_json) } : null }; }
export async function refreshCeremonyContext(db: Db, id: string, client?: JiraClient, jiraBaseUrl?: string | null): Promise<{ ceremony: Ceremony; context: Awaited<ReturnType<typeof refreshSprintContext>> }> { const row = getRow(db, id); const keys = row.kind === 'planning' ? db.prepare('SELECT work_item_key FROM sprint_plan_item WHERE ceremony_id = ? ORDER BY position').all(id).map((entry: any) => entry.work_item_key) as string[] : null; const refreshed = await refreshSprintContext(db, client, { teamId: row.team_id, sprintId: row.sprint_id, selectedKeys: keys, jiraBaseUrl }); const prior = db.prepare('SELECT payload_json FROM sprint_ceremony_draft_context WHERE ceremony_id = ?').get(id) as { payload_json: string } | undefined; if (refreshed.freshness !== 'fresh' && prior) { try { return { ceremony: ceremony(row), context: { ...JSON.parse(prior.payload_json), freshness: 'stale', errorMessage: refreshed.errorMessage } }; } catch { /* discard a malformed local draft candidate */ } } if (refreshed.freshness === 'fresh') db.prepare('INSERT INTO sprint_ceremony_draft_context (ceremony_id, captured_at, source, freshness, truncated, error_message, payload_json) VALUES (?, ?, ?, ?, ?, ?, ?) ON CONFLICT(ceremony_id) DO UPDATE SET captured_at = excluded.captured_at, source = excluded.source, freshness = excluded.freshness, truncated = excluded.truncated, error_message = excluded.error_message, payload_json = excluded.payload_json').run(id, now(), refreshed.source, refreshed.freshness, refreshed.truncated ? 1 : 0, refreshed.errorMessage ?? null, JSON.stringify(refreshed)); return { ceremony: ceremony(row), context: refreshed }; }
export function listCeremonies(db: Db, teamId: string, kind?: CeremonyKind): Ceremony[] { return db.prepare(`SELECT * FROM sprint_ceremony WHERE team_id = ? ${kind ? 'AND kind = ?' : ''} ORDER BY sprint_start_date DESC, created_at DESC`).all(...(kind ? [teamId, kind] : [teamId])).map(ceremony); }
export function openCeremony(db: Db, input: { teamId?: unknown; sprintId?: unknown; kind?: unknown }): CeremonyAggregate { if (typeof input.teamId !== 'string' || typeof input.sprintId !== 'string' || !kinds.has(input.kind as CeremonyKind)) throw badRequest('teamId, sprintId, and valid kind are required'); const id = db.transaction(() => { const existing = db.prepare('SELECT id FROM sprint_ceremony WHERE team_id = ? AND sprint_id = ? AND kind = ?').get(input.teamId, input.sprintId, input.kind) as any; if (existing) return existing.id; const sprint = db.prepare('SELECT * FROM sprint WHERE id = ? AND team_id = ?').get(input.sprintId, input.teamId) as any; if (!sprint) throw notFound(`Sprint ${input.sprintId} not found for team`); const baseline = input.kind === 'review' ? db.prepare(`SELECT active_snapshot_id FROM sprint_ceremony WHERE team_id = ? AND sprint_id = ? AND kind = 'planning' AND status = 'finalized' ORDER BY finalized_at DESC LIMIT 1`).get(input.teamId, input.sprintId) as any : null; const id = `ceremony_${randomUUID()}`, timestamp = now(); db.prepare(`INSERT INTO sprint_ceremony (id, team_id, sprint_id, sprint_name, sprint_start_date, sprint_end_date, kind, status, comparison_snapshot_id, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, 'draft', ?, ?, ?)`).run(id, input.teamId, input.sprintId, sprint.name, sprint.start_date, sprint.end_date, input.kind, baseline?.active_snapshot_id ?? null, timestamp, timestamp); return id; })(); return getCeremony(db, id); }
export function setPlanItem(db: Db, id: string, workItemKey: string, input: { expectedRevision?: unknown }): CeremonyAggregate { const expected = revision(input.expectedRevision); db.transaction(() => { const row = getRow(db, id); mutable(row, expected); if (row.kind !== 'planning') throw conflict('Only Planning ceremonies have commitments'); const item = db.prepare('SELECT 1 FROM work_item w JOIN user_story s ON s.key = w.story_key JOIN epic e ON e.key = s.epic_key WHERE w.key = ? AND e.team_id = ?').get(workItemKey, row.team_id); if (!item) throw notFound(`Work item ${workItemKey} not found for this ceremony team`); const count = (db.prepare('SELECT COUNT(*) AS n FROM sprint_plan_item WHERE ceremony_id = ?').get(id) as any).n; db.prepare('INSERT OR IGNORE INTO sprint_plan_item (ceremony_id, work_item_key, position, added_at) VALUES (?, ?, ?, ?)').run(id, workItemKey, count, now()); touch(db, id); })(); return getCeremony(db, id); }
export function removePlanItem(db: Db, id: string, workItemKey: string, input: { expectedRevision?: unknown }): CeremonyAggregate { const expected = revision(input.expectedRevision); db.transaction(() => { const row = getRow(db, id); mutable(row, expected); if (row.kind !== 'planning') throw conflict('Only Planning ceremonies have commitments'); if (!db.prepare('DELETE FROM sprint_plan_item WHERE ceremony_id = ? AND work_item_key = ?').run(id, workItemKey).changes) throw notFound(`Plan item ${workItemKey} not found`); reindexPlan(db, id); touch(db, id); })(); return getCeremony(db, id); }
export function reorderPlanItems(db: Db, id: string, input: { expectedRevision?: unknown; workItemKeys?: unknown }): CeremonyAggregate { const expected = revision(input.expectedRevision); if (!Array.isArray(input.workItemKeys) || input.workItemKeys.some((key) => typeof key !== 'string')) throw badRequest('workItemKeys must be an ordered array of keys'); db.transaction(() => { const row = getRow(db, id); mutable(row, expected); if (row.kind !== 'planning') throw conflict('Only Planning ceremonies have commitments'); const existing = db.prepare('SELECT work_item_key FROM sprint_plan_item WHERE ceremony_id = ? ORDER BY position').all(id).map((item: any) => item.work_item_key); const next = input.workItemKeys as string[]; if (next.length !== existing.length || new Set(next).size !== next.length || next.some((key) => !existing.includes(key))) throw badRequest('workItemKeys must contain every selected plan item exactly once'); db.prepare('UPDATE sprint_plan_item SET position = position + 1000000 WHERE ceremony_id = ?').run(id); const update = db.prepare('UPDATE sprint_plan_item SET position = ? WHERE ceremony_id = ? AND work_item_key = ?'); next.forEach((key, index) => update.run(index, id, key)); touch(db, id); })(); return getCeremony(db, id); }
export function addNote(db: Db, id: string, input: any): CeremonyAggregate { const expected = revision(input?.expectedRevision); const body = typeof input?.body === 'string' ? input.body.trim() : ''; if (!body || body.length > 4000 || !targetKinds.has(input?.targetKind)) throw badRequest('Valid note body and targetKind are required'); db.transaction(() => { const row = getRow(db, id); mutable(row, expected); const timestamp = now(), noteId = `ceremony_note_${randomUUID()}`; const position = (db.prepare('SELECT COUNT(*) AS n FROM sprint_ceremony_note WHERE ceremony_id = ?').get(id) as any).n; db.prepare('INSERT INTO sprint_ceremony_note (id, ceremony_id, body, target_kind, target_key, target_label, target_value_json, position, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)').run(noteId, id, body, input.targetKind, typeof input.targetKey === 'string' ? input.targetKey : null, typeof input.targetLabel === 'string' && input.targetLabel.trim() ? input.targetLabel.trim() : 'General', input.targetValueJson == null ? null : JSON.stringify(input.targetValueJson), position, timestamp, timestamp); touch(db, id); })(); return getCeremony(db, id); }
export function updateNote(db: Db, id: string, noteId: string, input: any): CeremonyAggregate { const expected = revision(input?.expectedRevision); const body = typeof input?.body === 'string' ? input.body.trim() : ''; if (!body || body.length > 4000) throw badRequest('Note body must be 1–4000 characters'); db.transaction(() => { const row = getRow(db, id); mutable(row, expected); if (!db.prepare('UPDATE sprint_ceremony_note SET body = ?, updated_at = ? WHERE id = ? AND ceremony_id = ?').run(body, now(), noteId, id).changes) throw notFound(`Ceremony note ${noteId} not found`); touch(db, id); })(); return getCeremony(db, id); }
export function deleteNote(db: Db, id: string, noteId: string, input: any): CeremonyAggregate { const expected = revision(input?.expectedRevision); db.transaction(() => { const row = getRow(db, id); mutable(row, expected); if (!db.prepare('DELETE FROM sprint_ceremony_note WHERE id = ? AND ceremony_id = ?').run(noteId, id).changes) throw notFound(`Ceremony note ${noteId} not found`); const rows = db.prepare('SELECT id FROM sprint_ceremony_note WHERE ceremony_id = ? ORDER BY position').all(id) as any[]; const update = db.prepare('UPDATE sprint_ceremony_note SET position = ? WHERE id = ?'); rows.forEach((entry, index) => update.run(index, entry.id)); touch(db, id); })(); return getCeremony(db, id); }
export function reorderNotes(db: Db, id: string, input: { expectedRevision?: unknown; noteIds?: unknown }): CeremonyAggregate { const expected = revision(input.expectedRevision); if (!Array.isArray(input.noteIds) || input.noteIds.some((noteId) => typeof noteId !== 'string')) throw badRequest('noteIds must be an ordered array of note IDs'); db.transaction(() => { const row = getRow(db, id); mutable(row, expected); const existing = db.prepare('SELECT id FROM sprint_ceremony_note WHERE ceremony_id = ? ORDER BY position').all(id).map((entry: any) => entry.id); const next = input.noteIds as string[]; if (next.length !== existing.length || new Set(next).size !== next.length || next.some((noteId) => !existing.includes(noteId))) throw badRequest('noteIds must contain every ceremony note exactly once'); db.prepare('UPDATE sprint_ceremony_note SET position = position + 1000000 WHERE ceremony_id = ?').run(id); const update = db.prepare('UPDATE sprint_ceremony_note SET position = ? WHERE ceremony_id = ? AND id = ?'); next.forEach((noteId, index) => update.run(index, id, noteId)); touch(db, id); })(); return getCeremony(db, id); }
export function finalizeCeremony(db: Db, id: string, input: { expectedRevision?: unknown; payload?: unknown }, suppliedContext?: Awaited<ReturnType<typeof refreshSprintContext>>): CeremonyAggregate { const expected = revision(input.expectedRevision); db.transaction(() => { const row = getRow(db, id); mutable(row, expected); const purpose = row.kind === 'planning' ? 'planning-baseline' : 'review-outcome'; const version = (db.prepare('SELECT COALESCE(MAX(version), 0) + 1 AS n FROM sprint_ceremony_snapshot WHERE ceremony_id = ?').get(id) as any).n; const snapshotId = `ceremony_snapshot_${randomUUID()}`, timestamp = now(); const keys = row.kind === 'planning' ? db.prepare('SELECT work_item_key FROM sprint_plan_item WHERE ceremony_id = ? ORDER BY position').all(id).map((entry: any) => entry.work_item_key) as string[] : null; const context = suppliedContext ?? buildStoredSprintContext(db, row.team_id, row.sprint_id, keys); if (row.kind === 'planning' && keys?.some((key) => !context.items.some((item) => item.key === key))) throw conflict('Refresh the selected commitment before finalizing; one or more plan items are missing from the source.'); const payload = { schemaVersion: 1, capturedAt: timestamp, ...context, capacity: capacitySnapshot(db, row) }; db.prepare('INSERT INTO sprint_ceremony_snapshot (id, ceremony_id, version, purpose, schema_version, captured_at, source, freshness, truncated, payload_json) VALUES (?, ?, ?, ?, 1, ?, ?, ?, ?, ?)').run(snapshotId, id, version, purpose, timestamp, context.source, context.freshness, context.truncated ? 1 : 0, JSON.stringify(payload)); db.prepare('UPDATE sprint_ceremony SET status = ?, active_snapshot_id = ?, finalized_at = ?, revision = revision + 1, updated_at = ? WHERE id = ?').run(row.kind === 'planning' ? 'finalized' : 'completed', snapshotId, timestamp, timestamp, id); })(); return getCeremony(db, id); }
export function reopenPlanningCeremony(db: Db, id: string, input: { expectedRevision?: unknown }): CeremonyAggregate { const expected = revision(input.expectedRevision); db.transaction(() => { const row = getRow(db, id); if (row.kind !== 'planning' || row.status !== 'finalized') throw conflict('Only finalized Planning ceremonies can be reopened'); if (row.revision !== expected) throw conflict('This ceremony changed in another tab; reload and try again'); db.prepare("UPDATE sprint_ceremony SET status = 'draft', revision = revision + 1, updated_at = ? WHERE id = ?").run(now(), id); })(); return getCeremony(db, id); }
function touch(db: Db, id: string): void { db.prepare('UPDATE sprint_ceremony SET revision = revision + 1, updated_at = ? WHERE id = ?').run(now(), id); }
function reindexPlan(db: Db, id: string): void { const rows = db.prepare('SELECT work_item_key FROM sprint_plan_item WHERE ceremony_id = ? ORDER BY position').all(id) as any[]; const update = db.prepare('UPDATE sprint_plan_item SET position = ? WHERE ceremony_id = ? AND work_item_key = ?'); rows.forEach((row, index) => update.run(index, id, row.work_item_key)); }
