export type SprintReviewItem = { key: string; points: number | null; status: string; epicKey: string | null; assigneeMemberId: string | null; assigneeMemberName?: string | null };
export type SprintReviewRow = { key: string; label?: string; committedPoints: number; donePoints: number; inReviewPoints: number; unfinishedPoints: number };
export type SprintReviewSummary = { baselineCaptured: boolean; committedKeys: string[]; addedKeys: string[]; removedKeys: string[]; statusCounts: Record<string, number>; statusPoints: Record<string, number>; unestimatedCount: number; committedPoints: number; completedCommittedPoints: number; epicRows: SprintReviewRow[]; memberRows: SprintReviewRow[] };
const points = (item: SprintReviewItem | undefined) => item?.points ?? 0;
const status = (item: SprintReviewItem | undefined) => item?.status ?? 'Missing';
function rowFor(rows: Map<string, SprintReviewRow>, key: string): SprintReviewRow { const existing = rows.get(key); if (existing) return existing; const next = { key, committedPoints: 0, donePoints: 0, inReviewPoints: 0, unfinishedPoints: 0 }; rows.set(key, next); return next; }
/** Derives stable, non-ranked sprint review facts from immutable item snapshots. */
export function summarizeSprintReview(baseline: readonly SprintReviewItem[] | null, outcome: readonly SprintReviewItem[]): SprintReviewSummary {
  const committed = new Map((baseline ?? []).map((item) => [item.key, item])); const current = new Map(outcome.map((item) => [item.key, item])); const statusCounts: Record<string, number> = {}; const statusPoints: Record<string, number> = {}; const epicRows = new Map<string, SprintReviewRow>(); const memberRows = new Map<string, SprintReviewRow>(); let committedPoints = 0, completedCommittedPoints = 0, unestimatedCount = 0;
  for (const item of outcome) { statusCounts[item.status] = (statusCounts[item.status] ?? 0) + 1; statusPoints[item.status] = (statusPoints[item.status] ?? 0) + points(item); if (item.points === null) unestimatedCount += 1; }
  for (const [key, original] of committed) { const observed = current.get(key); const estimate = points(original); const epic = rowFor(epicRows, original.epicKey ?? 'Unattributed'); const member = rowFor(memberRows, original.assigneeMemberId ?? 'Unassigned'); member.label ??= original.assigneeMemberName ?? undefined; committedPoints += estimate; epic.committedPoints += estimate; member.committedPoints += estimate; for (const row of [epic, member]) { if (status(observed) === 'Done') row.donePoints += estimate; else if (status(observed) === 'In Review') row.inReviewPoints += estimate; else row.unfinishedPoints += estimate; } if (status(observed) === 'Done') completedCommittedPoints += estimate; }
  const sorted = (rows: Map<string, SprintReviewRow>) => [...rows.values()].sort((a, b) => a.key.localeCompare(b.key));
  return { baselineCaptured: baseline !== null, committedKeys: [...committed.keys()].sort(), addedKeys: outcome.filter((item) => !committed.has(item.key)).map((item) => item.key).sort(), removedKeys: [...committed.keys()].filter((key) => !current.has(key)).sort(), statusCounts, statusPoints, unestimatedCount, committedPoints, completedCommittedPoints, epicRows: sorted(epicRows), memberRows: sorted(memberRows) };
}
