import { useEffect, useMemo, useState } from 'react';
import type { EngineerSprintOutput, TeamMember, TeamSprintOutput } from '@ecp/shared';
import * as api from '../data/api';
import { engineerSprintOutputModel } from '../lib/engineerSprintOutput';
import { MemberAvatar } from './MemberAvatar';

type SprintOutputSort = 'jira' | 'output-desc' | 'scope-desc' | 'name-asc';

export function EngineerSprintOutput({ teamId, members, selectedMemberId, colors, connected }: { teamId: string; members: TeamMember[]; selectedMemberId: string; colors: Map<string, string>; connected: boolean }) {
  const [result, setResult] = useState<TeamSprintOutput | null>(null); const [loading, setLoading] = useState(false); const [sort, setSort] = useState<SprintOutputSort>('jira');
  const load = () => { if (!connected) return; setLoading(true); api.getCurrentSprintOutput(teamId).then(setResult).catch((error) => setResult({ teamId, jiraBoardUrl: null, sprint: null, capturedAt: new Date().toISOString(), freshness: 'unavailable', truncated: false, errorMessage: error instanceof Error ? error.message : 'Sprint output unavailable.', engineers: [], unattributed: { itemCount: 0, estimatedDoneOrReviewPoints: 0, unestimatedDoneOrReviewItems: 0 } })).finally(() => setLoading(false)); };
  useEffect(() => { setResult(null); load(); }, [teamId, connected]); // lazy component only mounts for this view
  const byId = useMemo(() => new Map(members.map((member) => [member.id, member])), [members]);
  const rows = useMemo(() => { const scoped = result?.engineers.filter((engineer) => !selectedMemberId || engineer.memberId === selectedMemberId) ?? []; return sort === 'jira' ? scoped : scoped.slice().sort((left, right) => compareSprintOutput(left, right, byId, sort)); }, [byId, result, selectedMemberId, sort]);
  if (!connected) return <section className="panel sprint-output"><h2>Sprint output</h2><p className="hint">Live Jira sprint output requires the backend.</p></section>;
  if (!result && loading) return <section className="panel sprint-output" role="status">Loading current Jira sprint output…</section>;
  if (!result) return null;
  return <section className="panel sprint-output" aria-live="polite"><div className="section-title"><div><h2>Sprint output{result.sprint ? ` — ${result.sprint.name}` : ''}</h2><span className="hint">Done and In Review points for currently assigned work compared with PTO/on-call-adjusted sprint capacity.</span></div><div className="sprint-output-actions"><label className="control sprint-output-sort"><span>Sort</span><select aria-label="Sort sprint output" value={sort} onChange={(event) => setSort(event.target.value as SprintOutputSort)}><option value="jira">Jira order</option><option value="output-desc">Output, highest first</option><option value="scope-desc">Total scope, highest first</option><option value="name-asc">Engineer name, A–Z</option></select></label><button type="button" className="btn" disabled={loading} onClick={load}>{loading ? 'Retrying…' : 'Retry'}</button></div></div>
    {result.sprint?.startDate && result.sprint.endDate && <p className="hint">{result.sprint.startDate} to {result.sprint.endDate}</p>}
    {result.errorMessage && <p className="sprint-output-warning" role="alert">{result.errorMessage}</p>}
    {result.truncated && <p className="sprint-output-warning">Jira returned a partial result; output totals are incomplete and ratios are hidden.</p>}
    <div className="sprint-output-gauge-guide"><ul className="sprint-output-gauge-legend" aria-label="Sprint output gauge legend"><li><span className="sprint-output-gauge-key sprint-output-done" aria-hidden="true" />Done</li><li><span className="sprint-output-gauge-key sprint-output-review" aria-hidden="true" />In review</li><li><span className="sprint-output-gauge-key sprint-output-progress" aria-hidden="true" />In progress</li><li><span className="sprint-output-gauge-key sprint-output-todo" aria-hidden="true" />To do</li></ul><p className="hint">Output % = (Done + In review) ÷ available capacity</p></div>
    {rows.map((engineer) => { const member = byId.get(engineer.memberId); if (!member) return null; const model = engineerSprintOutputModel(engineer, result.truncated); const totalScope = model.done + model.review + model.inProgress + model.toDo; const scopePercent = roundScope(model); const overCapacity = typeof scopePercent === 'number' && scopePercent > 100; const overage = model.capacity === null ? 0 : totalScope - model.capacity; const label = !engineer.jiraLinked ? 'Jira account not linked' : model.capacity === null ? 'Capacity unavailable' : `${model.done} Done + ${model.review} In Review / ${model.capacity} available pts${model.percent === null ? '' : ` · ${model.percent}%`}`; const boardHref = result.jiraBoardUrl && member.jiraAccountId ? `${result.jiraBoardUrl}?assignee=${encodeURIComponent(member.jiraAccountId)}` : null; const scopeLabel = `${member.name}: ${label}. Including ${model.inProgress} In Progress and ${model.toDo} To Do points, assigned scope reaches ${scopePercent} available-capacity percent.`; return <article key={engineer.memberId} className="sprint-output-row" aria-label={`${member.name}: ${label}`}><div className="sprint-output-member"><MemberAvatar name={member.name} color={colors.get(member.id) ?? '#6b7280'} size={28} avatarUrl={member.avatarUrl} />{boardHref ? <a className="sprint-output-member-link" href={boardHref} target="_blank" rel="noreferrer" aria-label={`Open ${member.name}'s Jira board view`} title="Open filtered Jira board">{member.name} <span aria-hidden="true">↗</span></a> : <strong>{member.name}</strong>}</div>{!engineer.jiraLinked ? <p className="hint">Link this member to Jira in Configuration. {model.capacity ?? '—'} available pts.</p> : <><strong className="sprint-output-totals">{label}</strong>{model.capacity !== null && model.percent !== null && <><div className="sprint-output-gauge" role="img" aria-label={scopeLabel}><span className="sprint-output-todo" style={{ width: `${model.totalScopeWidth}%` }} /><span className="sprint-output-progress" style={{ width: `${model.inProgressTotalWidth}%` }} /><span className="sprint-output-review" style={{ width: `${model.doneReviewWidth}%` }} /><span className="sprint-output-done" style={{ width: `${model.doneWidth}%` }} /></div><p className="sprint-output-legend"><span>Done {model.done}</span><span>Review {model.review}</span><span>In progress {model.inProgress}</span><span>To do {model.toDo}</span></p><p className={`sprint-output-scope${overCapacity ? ' is-over-capacity' : ''}`}>{totalScope} assigned / {model.capacity} available pts · {scopePercent}% scoped{overCapacity && ` · ${overage} pt${overage === 1 ? '' : 's'} over capacity`}</p></>}<p className="hint">{engineer.baseVelocity} base → {model.capacity ?? '—'} available{engineer.unestimatedDoneOrReviewItems ? ` · ${engineer.unestimatedDoneOrReviewItems} unestimated recognized item${engineer.unestimatedDoneOrReviewItems === 1 ? '' : 's'} excluded` : ''}</p></>}</article>; })}
    {!rows.length && !result.errorMessage && <p className="hint">No active team members match this filter.</p>}
    {result.unattributed.itemCount > 0 && <p className="sprint-output-warning">{result.unattributed.itemCount} recognized sprint item{result.unattributed.itemCount === 1 ? '' : 's'} could not be attributed to an active linked team member.</p>}
  </section>;
}

function roundScope(model: ReturnType<typeof engineerSprintOutputModel>): number | string {
  return model.capacity && model.capacity > 0 ? Math.round((model.done + model.review + model.inProgress + model.toDo) / model.capacity * 100) : 'unknown';
}

function compareSprintOutput(left: EngineerSprintOutput, right: EngineerSprintOutput, members: Map<string, TeamMember>, sort: Exclude<SprintOutputSort, 'jira'>): number {
  const leftOutput = left.donePoints + left.inReviewPoints;
  const rightOutput = right.donePoints + right.inReviewPoints;
  const leftScope = leftOutput + left.inProgressPoints + left.toDoPoints;
  const rightScope = rightOutput + right.inProgressPoints + right.toDoPoints;
  const nameComparison = (members.get(left.memberId)?.name ?? '').localeCompare(members.get(right.memberId)?.name ?? '');
  if (sort === 'name-asc') return nameComparison;
  return (sort === 'output-desc' ? rightOutput - leftOutput : rightScope - leftScope) || nameComparison;
}
