import { describeAnnualHolidayRecurrence, holidayOccurrenceForYear, type AnnualHolidayRecurrence, type DomainDataset, type TeamHoliday, type Weekday } from '@ecp/shared';
import { useEffect, useMemo, useState } from 'react';
import * as api from '../data/api';

const months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];
const weekdays = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];

export function TrackedHolidays({ dataset, editable, onEdit, onAdd }: { dataset: DomainDataset; editable: boolean; onEdit: (holiday: TeamHoliday) => void; onAdd: () => void }) {
  const teamNames = useMemo(() => new Map(dataset.teams.map((team) => [team.id, team.name])), [dataset.teams]);
  const currentYear = new Date().getUTCFullYear();
  const rules = (dataset.holidays ?? []).slice().sort((a, b) => a.name.localeCompare(b.name) || a.teamId.localeCompare(b.teamId));
  return <section className="panel tracked-holidays" aria-labelledby="tracked-holidays-title">
    <div className="section-title"><div><h2 id="tracked-holidays-title">Tracked holidays</h2><span className="hint">Annual rules are applied to team capacity every year.</span></div>{editable && <button type="button" className="btn primary" onClick={onAdd}>Add holiday</button>}</div>
    {rules.length === 0 ? <p className="calendar-empty">No team holidays are tracked yet.</p> : <div className="holiday-rule-list">{rules.map((holiday) => {
      const occurrence = holiday.recurrence ? holidayOccurrenceForYear(holiday, currentYear) : null;
      return <div className="holiday-rule-row" key={holiday.id}><div><strong>{holiday.name}</strong><span>{teamNames.get(holiday.teamId) ?? holiday.teamId} · {holiday.recurrence ? describeAnnualHolidayRecurrence(holiday.recurrence) : holiday.date}</span></div><div className="holiday-rule-next"><span>{occurrence ? `Next: ${occurrence.date}${occurrence.observed ? ' (observed)' : ''}` : 'Legacy date rule'}</span>{editable && <button type="button" className="link-btn" onClick={() => onEdit(holiday)}>Edit</button>}</div></div>;
    })}</div>}
  </section>;
}

export function HolidayRuleModal({ dataset, holiday, onClose, onSaved }: { dataset: DomainDataset; holiday: TeamHoliday | null; onClose: () => void; onSaved: () => Promise<void> }) {
  const defaultTeamId = dataset.teams[0]?.id ?? '';
  const initial = holiday?.recurrence ?? { kind: 'fixed-date', month: 1, day: 1, observedPolicy: 'none' } satisfies AnnualHolidayRecurrence;
  const [name, setName] = useState(holiday?.name ?? '');
  const [teamId, setTeamId] = useState(holiday?.teamId ?? defaultTeamId);
  const [recurrence, setRecurrence] = useState<AnnualHolidayRecurrence>(initial);
  const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  useEffect(() => { const close = (event: KeyboardEvent) => { if (event.key === 'Escape' && !busy) onClose(); }; document.addEventListener('keydown', close); return () => document.removeEventListener('keydown', close); }, [busy, onClose]);
  const setKind = (kind: AnnualHolidayRecurrence['kind']) => setRecurrence(kind === 'fixed-date' ? { kind, month: 1, day: 1, observedPolicy: 'none' } : { kind, month: 9, weekday: 1, ordinal: 1, observedPolicy: 'none' });
  const save = async () => { if (!name.trim() || !teamId) return; setBusy(true); setError(null); try { if (holiday) await api.updateTeamHoliday(teamId, holiday.id, { name: name.trim(), recurrence }); else await api.createTeamHoliday(teamId, { name: name.trim(), recurrence }); await onSaved(); onClose(); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } finally { setBusy(false); } };
  const remove = async () => { if (!holiday) return; setBusy(true); setError(null); try { await api.deleteTeamHoliday(teamId, holiday.id); await onSaved(); onClose(); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } finally { setBusy(false); } };
  return <div className="modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget && !busy) onClose(); }}><section className="modal holiday-rule-modal" role="dialog" aria-modal="true" aria-labelledby="holiday-rule-title">
    <div className="modal-heading"><div><h2 id="holiday-rule-title">{holiday ? 'Edit holiday' : 'Add holiday'}</h2><p className="hint">The rule repeats annually and reduces the selected team’s capacity.</p></div><button type="button" className="modal-close" aria-label="Close holiday dialog" disabled={busy} onClick={onClose}>×</button></div>
    <div className="holiday-rule-fields"><label className="control"><span>Name</span><input type="text" autoFocus value={name} disabled={busy} placeholder="Labor Day" onChange={(event) => setName(event.target.value)} /></label><label className="control"><span>Team</span><select value={teamId} disabled={busy || Boolean(holiday)} onChange={(event) => setTeamId(event.target.value)}>{dataset.teams.map((team) => <option value={team.id} key={team.id}>{team.name}</option>)}</select></label><label className="control"><span>Repeats</span><select value={recurrence.kind} disabled={busy} onChange={(event) => setKind(event.target.value as AnnualHolidayRecurrence['kind'])}><option value="fixed-date">On a fixed date</option><option value="nth-weekday">On a weekday pattern</option></select></label>
      {recurrence.kind === 'fixed-date' ? <><label className="control"><span>Month</span><select value={recurrence.month} disabled={busy} onChange={(event) => setRecurrence({ ...recurrence, month: Number(event.target.value) })}>{months.map((month, index) => <option value={index + 1} key={month}>{month}</option>)}</select></label><label className="control"><span>Day</span><input type="number" min="1" max="31" value={recurrence.day} disabled={busy} onChange={(event) => setRecurrence({ ...recurrence, day: Number(event.target.value) })} /></label><label className="inline-check holiday-observed"><input type="checkbox" checked={recurrence.observedPolicy === 'nearest-weekday'} disabled={busy} onChange={(event) => setRecurrence({ ...recurrence, observedPolicy: event.target.checked ? 'nearest-weekday' : 'none' })} /> Observe on nearest weekday when it falls on a weekend</label></> : <><label className="control"><span>Month</span><select value={recurrence.month} disabled={busy} onChange={(event) => setRecurrence({ ...recurrence, month: Number(event.target.value) })}>{months.map((month, index) => <option value={index + 1} key={month}>{month}</option>)}</select></label><label className="control"><span>Weekday</span><select value={recurrence.weekday} disabled={busy} onChange={(event) => setRecurrence({ ...recurrence, weekday: Number(event.target.value) as Weekday })}>{weekdays.map((weekday, index) => <option value={index} key={weekday}>{weekday}</option>)}</select></label><label className="control"><span>Which one</span><select value={recurrence.ordinal} disabled={busy} onChange={(event) => setRecurrence({ ...recurrence, ordinal: event.target.value === 'last' ? 'last' : Number(event.target.value) as 1 | 2 | 3 | 4 })}><option value="1">First</option><option value="2">Second</option><option value="3">Third</option><option value="4">Fourth</option><option value="last">Last</option></select></label></>}</div>
    <p className="holiday-rule-preview">{describeAnnualHolidayRecurrence(recurrence)}</p>{error && <p className="modal-error" role="alert">{error}</p>}<div className="modal-actions">{holiday && <button type="button" className="btn danger" disabled={busy} onClick={() => void remove()}>Delete</button>}<span /><button type="button" className="btn" disabled={busy} onClick={onClose}>Cancel</button><button type="button" className="btn primary" disabled={busy || !name.trim() || !teamId} onClick={() => void save()}>{busy ? 'Saving…' : holiday ? 'Save holiday' : 'Add holiday'}</button></div>
  </section></div>;
}
