import { useCallback, useEffect, useMemo, useState } from 'react';
import { type DomainDataset, type ImportantDateIconKey } from '@ecp/shared';
import * as api from '../data/api';
import { IMPORTANT_DATE_ICON_OPTIONS, ImportantDateIcon } from './ImportantDateIcon';
import { IconPicker } from './IconPicker';
import { fuzzyScore } from '../lib/fuzzySearch';
import { Typeahead, type TypeaheadOption } from './Typeahead';
import { DatePicker } from './DatePicker';

const today = () => new Date().toISOString().slice(0, 10);

type RelevantDayKind = 'global' | 'epic' | 'availability';
const availabilityTypes = [{ id: 'pto', label: 'PTO' }, { id: 'oncall', label: 'On-call' }] as const satisfies readonly TypeaheadOption[];
const epicDateNameOptions = [{ id: 'code-freeze', label: 'Code freeze' }, { id: 'qa-signoff', label: 'QA sign-off' }, { id: 'launch', label: 'Launch' }, { id: 'planning-deadline', label: 'Planning deadline' }] as const satisfies readonly TypeaheadOption[];
const searchAvailabilityTypes = async (query: string): Promise<TypeaheadOption[]> => {
  const normalized = query.trim().toLowerCase();
  return availabilityTypes.filter((option) => !normalized || option.label.toLowerCase().includes(normalized));
};
const searchEpicDateNames = async (query: string): Promise<TypeaheadOption[]> => {
  const normalized = query.trim().toLowerCase();
  return epicDateNameOptions.filter((option) => !normalized || option.label.toLowerCase().includes(normalized));
};

/** Focused Calendar creation surface for every date that changes planning context. */
export function AddRelevantDayModal({ dataset, onClose, onReload }: { dataset: DomainDataset; onClose: () => void; onReload: () => Promise<void> }) {
  const activeEpics = useMemo(() => dataset.epics.filter((epic) => epic.active !== false), [dataset.epics]); const defaultEpic = activeEpics[0];
  const [kind, setKind] = useState<RelevantDayKind>('global'); const [name, setName] = useState(''); const [date, setDate] = useState(today()); const [iconKey, setIconKey] = useState<ImportantDateIconKey | null>('calendar'); const [linkUrl, setLinkUrl] = useState(''); const [notes, setNotes] = useState(''); const [epicKey, setEpicKey] = useState(defaultEpic?.key ?? ''); const [epicText, setEpicText] = useState(defaultEpic ? `${defaultEpic.key} · ${defaultEpic.title}` : ''); const [isGating, setIsGating] = useState(false); const [memberId, setMemberId] = useState(dataset.members.find((member) => member.active)?.id ?? ''); const [availabilityKind, setAvailabilityKind] = useState<'pto' | 'oncall' | null>('pto'); const [availabilityTypeText, setAvailabilityTypeText] = useState('PTO'); const [endDate, setEndDate] = useState(today()); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  const searchEpics = useCallback(async (query: string): Promise<TypeaheadOption[]> => { const normalized = query.trim().toLowerCase(); return activeEpics.filter((epic) => !normalized || `${epic.key} ${epic.title}`.toLowerCase().includes(normalized)).map((epic) => ({ id: epic.key, label: `${epic.key} · ${epic.title}` })); }, [activeEpics]);
  useEffect(() => { const close = (event: KeyboardEvent) => { if (event.key === 'Escape' && !busy) onClose(); }; document.addEventListener('keydown', close); return () => document.removeEventListener('keydown', close); }, [busy, onClose]);
  const valid = kind === 'global' ? Boolean(name.trim() && date && iconKey) : kind === 'epic' ? Boolean(name.trim() && date && epicKey) : Boolean(memberId && availabilityKind && date && endDate && endDate >= date);
  const save = async () => { if (kind === 'global' && !iconKey) return; setBusy(true); setError(null); try { if (kind === 'global') await api.createImportantDate({ name: name.trim(), date, iconKey: iconKey!, linkUrl, notes }); else if (kind === 'epic') await api.createMilestone(epicKey, { name: name.trim(), date, isGating }); else if (availabilityKind === 'pto') await api.createPto({ memberId, startDate: date, endDate, note: notes }); else await api.createOncall({ memberId, startDate: date, endDate, note: notes }); await onReload(); onClose(); } catch (reason) { setError(reason instanceof Error ? reason.message : String(reason)); } finally { setBusy(false); } };
  const copy: Record<RelevantDayKind, string> = { global: 'Portfolio-wide context that remains visible under every epic filter.', epic: 'A relevant day attached to one epic. It follows the current epic filter.', availability: 'PTO or on-call time that changes a team member’s available capacity.' };
  return <div className="modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget && !busy) onClose(); }}><section className="modal important-date-modal" role="dialog" aria-modal="true" aria-labelledby="important-date-modal-title">
    <div className="modal-heading"><div><h2 id="important-date-modal-title">Add relevant day</h2><p className="hint">{copy[kind]}</p></div><button type="button" className="modal-close" aria-label="Close add relevant day dialog" disabled={busy} onClick={onClose}>×</button></div>
    <div className="segmented relevant-day-kind" role="tablist" aria-label="Relevant day type">{([['global', 'Global date'], ['epic', 'Epic date'], ['availability', 'Availability']] as const).map(([value, label]) => <button type="button" key={value} role="tab" aria-selected={kind === value} className={`segment${kind === value ? ' active' : ''}`} onClick={() => setKind(value)}>{label}</button>)}</div>
    {kind === 'global' && <div className="important-date-modal-fields"><label className="control"><span>Name</span><input type="text" autoFocus value={name} disabled={busy} placeholder="Quarterly planning" onChange={(event) => setName(event.target.value)} /></label><label className="control"><span>Date</span><DatePicker value={date} disabled={busy} ariaLabel="Global date" onChange={setDate} /></label><IconPicker label="Icon" value={iconKey} options={IMPORTANT_DATE_ICON_OPTIONS} renderIcon={(key, className) => <ImportantDateIcon iconKey={key} className={className} />} disabled={busy} onChange={setIconKey} testId="important-date-icon-picker" /><label className="control"><span>Link</span><input type="url" value={linkUrl} disabled={busy} placeholder="https://…" onChange={(event) => setLinkUrl(event.target.value)} /></label><label className="control important-date-modal-notes"><span>Notes</span><textarea value={notes} disabled={busy} placeholder="Optional context" onChange={(event) => setNotes(event.target.value)} /></label></div>}
    {kind === 'epic' && <div className="important-date-modal-fields"><label className="control"><span>Epic</span><Typeahead value={epicText} disabled={busy} placeholder="Find an epic" searchOnEmpty debounceMs={0} showLoading={false} search={searchEpics} onFocus={() => { setEpicText(''); setEpicKey(''); }} onChange={(text) => { setEpicText(text); setEpicKey(''); }} onSelect={(option) => { setEpicKey(option.id); setEpicText(option.label); }} /></label><label className="control"><span>Date</span><DatePicker value={date} disabled={busy} ariaLabel="Epic date" onChange={setDate} /></label><label className="control important-date-modal-notes"><span>Name</span><Typeahead value={name} disabled={busy} placeholder="Code freeze" searchOnEmpty debounceMs={0} showLoading={false} search={searchEpicDateNames} onChange={setName} onSelect={(option) => setName(option.label)} /></label><label className="inline-check"><input type="checkbox" checked={isGating} disabled={busy} onChange={(event) => setIsGating(event.target.checked)} /> Gating day</label></div>}
    {kind === 'availability' && <div className="important-date-modal-fields availability-modal-fields"><MemberFuzzyPicker members={dataset.members.filter((member) => member.active)} value={memberId} disabled={busy} onChange={setMemberId} /><label className="control availability-type-select"><span>Availability type</span><Typeahead value={availabilityTypeText} disabled={busy} placeholder="Find availability type" searchOnEmpty debounceMs={0} showLoading={false} search={searchAvailabilityTypes} onFocus={() => { setAvailabilityTypeText(''); setAvailabilityKind(null); }} onChange={(text) => { setAvailabilityTypeText(text); setAvailabilityKind(null); }} onSelect={(option) => { const selected = option.id as 'pto' | 'oncall'; setAvailabilityKind(selected); setAvailabilityTypeText(option.label); }} /></label><label className="control"><span>Start date</span><DatePicker value={date} disabled={busy} ariaLabel="Start date" onChange={setDate} /></label><label className="control"><span>End date</span><DatePicker min={date} value={endDate} disabled={busy} ariaLabel="End date" onChange={setEndDate} /></label><label className="control important-date-modal-notes"><span>Note</span><textarea value={notes} disabled={busy} placeholder="Optional context" onChange={(event) => setNotes(event.target.value)} /></label></div>}
    {error && <p className="modal-error" role="alert">{error}</p>}<div className="modal-actions"><button type="button" className="btn" disabled={busy} onClick={onClose}>Cancel</button><button type="button" className="btn primary" disabled={busy || !valid} onClick={save}>{busy ? 'Adding…' : 'Add day'}</button></div>
  </section></div>;
}

function MemberFuzzyPicker({ members, value, disabled, onChange }: { members: DomainDataset['members']; value: string; disabled: boolean; onChange: (id: string) => void }) {
  const selected = members.find((member) => member.id === value);
  const [query, setQuery] = useState(() => selected?.name ?? '');
  useEffect(() => { if (value) setQuery(selected?.name ?? ''); }, [value, selected?.name]);
  const search = useCallback(async (text: string): Promise<TypeaheadOption[]> => members.map((member) => ({ member, score: fuzzyScore(member.name, text) })).filter((entry) => entry.score !== null).sort((a, b) => a.score! - b.score! || a.member.name.localeCompare(b.member.name)).map(({ member }) => ({ id: member.id, label: member.name })), [members]);
  return <label className="control member-fuzzy-picker"><span>Team member</span><Typeahead value={query} disabled={disabled} inputType="search" inputClassName="member-fuzzy-input" placeholder="Search team members" searchOnEmpty debounceMs={0} showLoading={false} search={search} onFocus={() => { setQuery(''); onChange(''); }} onChange={(text) => { setQuery(text); onChange(''); }} onSelect={(option) => { onChange(option.id); setQuery(option.label); }} /></label>;
}

/** Case-insensitive ordered-character matching, with strong preference for contiguous prefixes. */
