import type { StandupSprintProgressContext } from '@ecp/shared';
import { CircleMinus, TrendingDown, TrendingUp } from 'lucide-react';
import { deriveStandupSprintProgress } from '../lib/standupSprintProgress';

const asPercent = (value: number | null) => value === null ? '0%' : `${Math.round(value)}%`;
function signalTone(signal: string | null): 'ahead' | 'close' | 'behind' | null { return signal?.includes('ahead') ? 'ahead' : signal?.includes('behind') ? 'behind' : signal ? 'close' : null; }

export function SprintProgressGauge({ context, sessionDate, refreshing, onRetry }: { context: StandupSprintProgressContext | null; sessionDate: string; refreshing: boolean; onRetry: () => void }) {
  const model = deriveStandupSprintProgress(context, sessionDate); const tone = signalTone(model.signal);
  if (model.state === 'unavailable') return <section className="sprint-progress" aria-labelledby="sprint-progress-title"><h3 id="sprint-progress-title">Sprint progress</h3><p className="hint">{context?.errorMessage ?? 'Progress is unavailable while Jira is not connected.'}</p><button type="button" className="link-btn" disabled={refreshing} onClick={onRetry}>{refreshing ? 'Refreshing…' : 'Retry'}</button></section>;
  const SignalIcon = tone === 'ahead' ? TrendingUp : tone === 'behind' ? TrendingDown : CircleMinus;
  return <section className="sprint-progress" aria-labelledby="sprint-progress-title"><div className="sprint-progress-heading"><div><h3 id="sprint-progress-title">Sprint progress</h3><p className="hint">{model.totalItems} items · {model.totalPoints} estimated points · {model.unestimatedItems} unestimated</p></div>{context?.freshness === 'stale' && <button type="button" className="link-btn" disabled={refreshing} onClick={onRetry}>Retry</button>}</div>{context?.truncated && <p className="sprint-progress-warning">Partial Jira result — totals are incomplete.</p>}{model.state === 'empty' ? <p className="hint">This sprint has no items.</p> : model.totalPoints === 0 ? <p className="hint">No estimated points are available for a progress gauge.</p> : <><div className="sprint-gauge-time-label" style={{ left: asPercent(model.elapsedPercent) }}>Today{model.elapsedDays !== null ? ` · day ${model.elapsedDays} of ${model.totalDays}` : ''}</div><div className="sprint-gauge" role="img" aria-label={model.accessibleSummary}><div className="sprint-gauge-review" style={{ width: asPercent(model.reviewPercent) }} /><div className="sprint-gauge-done" style={{ width: asPercent(model.donePercent) }} />{model.elapsedPercent !== null && <span className="sprint-gauge-time" style={{ left: asPercent(model.elapsedPercent) }}>{tone && model.signal && <span className={`sprint-gauge-signal-marker is-${tone}`} tabIndex={0} aria-label={model.signal}><SignalIcon aria-hidden="true" size={16} /><span className="sprint-gauge-signal-tooltip" role="tooltip">{model.signal}</span></span>}</span>}</div><div className="sprint-gauge-legend" aria-label="Gauge legend"><span><i className="sprint-legend-swatch done" />Done · {model.points.Done} pts</span><span><i className="sprint-legend-swatch review" />In review · {model.points['In Review']} pts</span><span><i className="sprint-legend-swatch time" />Today · {model.elapsedDays ?? 'dates unavailable'}</span></div></>}<dl className="sprint-progress-breakdown"><div><dt>Done</dt><dd>{model.points.Done}</dd></div><div><dt>In review</dt><dd>{model.points['In Review']}</dd></div><div><dt>In progress</dt><dd>{model.points['In Progress']}</dd></div><div><dt>To do</dt><dd>{model.points['To Do']}</dd></div></dl>{context?.freshness === 'stale' && <p className="hint">Updated {new Date(context.capturedAt).toLocaleTimeString()} · refresh failed</p>}</section>;
}
