import { useEffect, useMemo, useRef, useState } from 'react';
import type { DomainDataset, StandupAudioMemberAssignment, StandupAudioTrackSummary, TeamStandupAudioSettings } from '@ecp/shared';
import * as api from '../data/api';
import { Typeahead } from './Typeahead';
import { MemberAvatar } from './MemberAvatar';
import { colorFor, memberColorMap } from '../lib/memberColors';

export function StandupAudioConfiguration({ dataset, teamId, disabled }: { dataset: DomainDataset; teamId: string | null; disabled: boolean }) {
  const [tracks, setTracks] = useState<StandupAudioTrackSummary[]>([]); const [settings, setSettings] = useState<TeamStandupAudioSettings | null>(null); const [error, setError] = useState<string | null>(null);
  const load = async () => { if (!teamId) return; try { const [nextTracks, nextSettings] = await Promise.all([api.listStandupAudioTracks(), api.getTeamStandupAudio(teamId)]); setTracks(nextTracks); setSettings(nextSettings); setError(null); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not load walk-off audio.'); } };
  useEffect(() => { void load(); }, [teamId]);
  if (!teamId) return null;
  const save = async (next: Omit<TeamStandupAudioSettings, 'teamId'>) => { try { setSettings(await api.saveTeamStandupAudio(teamId, next)); setError(null); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not save audio settings.'); } };
  return <section className="panel standup-audio-config"><div className="section-title"><div><h2>Walk-off audio</h2><span className="hint">MP3s are stored in this shareable database and play only after the facilitator enables audio. Upload only music you are allowed to use.</span></div></div><TrackLibrary tracks={tracks} disabled={disabled} onChanged={load} onError={setError} />{settings && <AudioAssignments dataset={dataset} tracks={tracks} settings={settings} disabled={disabled} onSave={save} />}{error && <p className="config-error" role="alert">{error}</p>}</section>;
}

function TrackLibrary({ tracks, disabled, onChanged, onError }: { tracks: StandupAudioTrackSummary[]; disabled: boolean; onChanged: () => Promise<void>; onError: (value: string | null) => void }) {
  const [file, setFile] = useState<File | null>(null); const [name, setName] = useState(''); const [busy, setBusy] = useState(false); const audio = useRef<HTMLAudioElement | null>(null); const [playing, setPlaying] = useState<string | null>(null);
  useEffect(() => () => { audio.current?.pause(); }, []);
  const upload = async () => { if (!file) return; setBusy(true); try { await api.uploadStandupAudioTrack(file, name.trim() || file.name.replace(/\.mp3$/i, '')); setFile(null); setName(''); await onChanged(); } catch (reason) { onError(reason instanceof Error ? reason.message : 'Upload failed.'); } finally { setBusy(false); } };
  const preview = (track: StandupAudioTrackSummary) => { if (playing === track.id) { audio.current?.pause(); setPlaying(null); return; } audio.current?.pause(); const next = new Audio(api.standupAudioContentUrl(track.id)); next.volume = .35; next.onended = () => setPlaying(null); audio.current = next; void next.play().then(() => setPlaying(track.id)).catch((reason) => onError(reason instanceof Error ? reason.message : 'Preview could not play.')); };
  return <div className="standup-audio-library"><label className="control"><span>Upload MP3 (12 MiB maximum)</span><input type="file" accept=".mp3,audio/mpeg" disabled={disabled || busy} onChange={(event) => { const next = event.currentTarget.files?.[0] ?? null; setFile(next); setName(next ? next.name.replace(/\.mp3$/i, '') : ''); }} /></label>{file && <div className="standup-audio-upload"><input type="text" value={name} aria-label="Track display name" onChange={(event) => setName(event.target.value)} disabled={disabled || busy} /><button type="button" className="btn primary" disabled={disabled || busy} onClick={() => void upload()}>{busy ? 'Uploading…' : 'Upload'}</button></div>}<div className="standup-audio-tracks">{tracks.length ? tracks.map((track) => <div className="standup-audio-track" key={track.id}><span><strong>♫ {track.displayName}</strong><small>{track.originalFilename} · {(track.byteLength / 1024 / 1024).toFixed(1)} MiB</small></span><div><button type="button" className="link-btn" onClick={() => preview(track)}>{playing === track.id ? 'Stop' : 'Preview'}</button><button type="button" className="link-btn danger" disabled={disabled} onClick={() => void api.deleteStandupAudioTrack(track.id).then(onChanged).catch((reason) => onError(reason instanceof Error ? reason.message : 'Could not delete track.'))}>Delete</button></div></div>) : <p className="hint">No walk-off songs uploaded yet.</p>}</div></div>;
}

function AudioAssignments({ dataset, tracks, settings, disabled, onSave }: { dataset: DomainDataset; tracks: StandupAudioTrackSummary[]; settings: TeamStandupAudioSettings; disabled: boolean; onSave: (value: Omit<TeamStandupAudioSettings, 'teamId'>) => Promise<void> }) {
  const [defaultText, setDefaultText] = useState(tracks.find((track) => track.id === settings.defaultTrackId)?.displayName ?? 'No default song'); const [editing, setEditing] = useState<string | null>(null); const colors = useMemo(() => memberColorMap(dataset.members), [dataset.members]);
  useEffect(() => setDefaultText(tracks.find((track) => track.id === settings.defaultTrackId)?.displayName ?? 'No default song'), [tracks, settings.defaultTrackId]);
  const options = [{ id: 'none', label: 'No default song' }, ...tracks.map((track) => ({ id: track.id, label: track.displayName, hint: track.originalFilename }))];
  const chooseDefault = (id: string | null) => void onSave({ defaultTrackId: id, memberAssignments: settings.memberAssignments.filter((entry) => entry.mode !== 'inherit') });
  const members = dataset.members.filter((member) => member.teamId === settings.teamId).sort((a, b) => Number(b.active) - Number(a.active) || a.name.localeCompare(b.name));
  const assignment = (memberId: string) => settings.memberAssignments.find((entry) => entry.memberId === memberId);
  return <div className="standup-audio-assignments"><label className="control"><span>Team default song</span><Typeahead value={defaultText} onChange={setDefaultText} selectedId={settings.defaultTrackId} disabled={disabled} search={async (query) => options.filter((track) => track.label.toLowerCase().includes(query.toLowerCase()))} onSelect={(option) => chooseDefault(option.id === 'none' ? null : option.id)} searchAllOnFocus selectValueOnFocus portalMenu debounceMs={0} showLoading={false} /></label>{members.map((member) => { const current = assignment(member.id); const label = current?.mode === 'off' ? 'No song' : current?.mode === 'track' ? tracks.find((track) => track.id === current.trackId)?.displayName ?? 'Missing song' : 'Uses team default'; return <div className={`standup-audio-member${member.active ? '' : ' inactive'}`} key={member.id}><MemberAvatar name={member.name} color={colorFor(colors, member.id)} size={28} avatarUrl={member.avatarUrl} /><span><strong>{member.name}</strong><small>{label}</small></span><button type="button" className="link-btn" disabled={disabled} onClick={() => setEditing(member.id)}>Edit</button>{editing === member.id && <MemberOverride memberId={member.id} tracks={tracks} assignment={current} onCancel={() => setEditing(null)} onSave={(next) => { const others = settings.memberAssignments.filter((entry) => entry.memberId !== member.id); void onSave({ defaultTrackId: settings.defaultTrackId, memberAssignments: next ? [...others, next] : others }).then(() => setEditing(null)); }} />}</div>; })}</div>;
}
function MemberOverride({ memberId, tracks, assignment, onCancel, onSave }: { memberId: string; tracks: StandupAudioTrackSummary[]; assignment?: StandupAudioMemberAssignment; onCancel: () => void; onSave: (value: StandupAudioMemberAssignment | null) => void }) { const [mode, setMode] = useState<'inherit' | 'off' | 'track'>(assignment?.mode ?? 'inherit'); const [trackId, setTrackId] = useState(assignment?.trackId ?? tracks[0]?.id ?? ''); return <div className="standup-audio-override" role="dialog" aria-label="Edit member walk-off song"><label><input type="radio" checked={mode === 'inherit'} onChange={() => setMode('inherit')} /> Inherit team default</label><label><input type="radio" checked={mode === 'off'} onChange={() => setMode('off')} /> No song</label><label><input type="radio" checked={mode === 'track'} onChange={() => setMode('track')} /> Custom song</label>{mode === 'track' && <select value={trackId} onChange={(event) => setTrackId(event.target.value)}>{tracks.map((track) => <option key={track.id} value={track.id}>{track.displayName}</option>)}</select>}<div><button type="button" className="btn primary" disabled={mode === 'track' && !trackId} onClick={() => onSave(mode === 'inherit' ? null : { memberId, mode, trackId: mode === 'track' ? trackId : null })}>Save</button><button type="button" className="btn" onClick={onCancel}>Cancel</button></div></div>; }
